### PR TITLE
Swap from guava cache to caffeine

### PR DESCRIPTION
**Pull request by res0nance**
Guava provided from core is a cache library that probably can't be updated ever, use an updated library.

I re-ran the benchmarks as well

image

### CODE REVIEW

**Comment by AbhyudayaSharma** [comment]
Wow! This is brilliant! 🎉

**Review by oleg-nenashev — CHANGES_REQUESTED** [review]
Definitely +1 from me for switching, thanks @res0nance !

I doubt we can do it as is though. There will be a version collision with the Script Security plugin: https://github.com/jenkinsci/script-security-plugin/blob/f5c52156f0ea37a308c517f7a94784f96a1256ed/pom.xml#L74-L78 . Since the Script Security plugin is installed almost on every Jenkins instance, maybe it makes sense to add a dependency on the plugin or externalize the library as an API plugin.

CC @dwnusbaum

**Comment by res0nance** [comment]
I'd vote for an API plugin, mostly due to if script-security drops caffeine for whatever reason this will just break role-strategy unintentionally. Perhaps Devin has a better idea.

**Comment by dwnusbaum** [comment]
In general, I would prefer to not add new plugin dependencies to `script-security`, although an API plugin would probably be fine. We could try shading `caffeine` in `script-security` since it is not intended to be exposed to other plugins anyway, but if I recall correctly, that only works if we make `script-security` a multi-module project (unless we are shading the library directly into the plugin's sources), which I would also prefer to avoid, so I'm not sure what approach would be best here.

**Comment by res0nance** [comment]
> In general, I would prefer to not add new plugin dependencies to `script-security`, although an API plugin would probably be fine. We could try shading `caffeine` in `script-security` since it is not intended to be exposed to other plugins anyway, but if I recall correctly, that only works if we make `script-security` a multi-module project (unless we are shading the library directly into the plugin's sources), which I would also prefer to avoid, so I'm not sure what approach would be best here.

We could add caffeine as a dep to core which means we would be able to move all of Core's guava cache usage to caffeine but updating caffeine in future might be tricky if has api breaks often.

**Comment by ben-manes** [comment]
@res0nance The Caffeine APIs do not break often and honors semver. However, there will be a break in 3.0 which is in active development. Those changes are small quality-of-life improvements and will not impact most users.

**Comment by dwnusbaum** [comment]
@res0nance I don't think we should ever intentionally add new dependencies to Jenkins core unless there is a way to hide them from plugins, since it just increases core's maintenance burden. To me an API plugin seems like the only realistic option here.

**Comment by res0nance** [comment]
> @res0nance I don't think we should ever intentionally add new dependencies to Jenkins core unless there is a way to hide them from plugins, since it just increases core's maintenance burden. To me an API plugin seems like the only realistic option here.

Looks like James is adding a new api plugin https://github.com/jenkinsci/caffeine-api-plugin will adapt this PR once that is released

**Comment by oleg-nenashev** [comment]
Thanks!

**Review by oleg-nenashev — APPROVED** [review]
Thanks @res0nance and @jtnord for making it possible!

**Pull request merged**
