### PR TITLE
Use ExtendedHierarchicalStreamReader to ensure compatibility with upstream XStream versions

### PR DESCRIPTION
**Pull request by jglick**
Compatibility with https://github.com/jenkinsci/jenkins/pull/4944.

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
Uh oh 

```
Suppressed: java.lang.OutOfMemoryError: GC overhead limit exceeded

[2020-09-24T23:11:25.924Z] 		at java.util.concurrent.ConcurrentLinkedQueue.offer(ConcurrentLinkedQueue.java:328)

[2020-09-24T23:11:25.924Z] 		at java.util.concurrent.ConcurrentLinkedQueue.add(ConcurrentLinkedQueue.java:297)

[2020-09-24T23:11:25.924Z] 		at com.google.common.cache.LocalCache$Segment.recordRead(LocalCache.java:2572)

[2020-09-24T23:11:25.924Z] 		at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2792)

[2020-09-24T23:11:25.924Z] 		at com.google.common.cache.LocalCache.getIfPresent(LocalCache.java:3954)

[2020-09-24T23:11:25.924Z] 		at com.google.common.cache.LocalCache$LocalManualCache.getIfPresent(LocalCache.java:4758)

[2020-09-24T23:11:25.924Z] 		at com.michelin.cio.hudson.plugins.rolestrategy.RoleMap.newMatchingRoleMap(RoleMap.java:412)

[2020-09-24T23:11:25.924Z] 		at jmh.benchmarks.FolderAccessBenchmark.benchmarkNewMatchingRoleMap(FolderAccessBenchmark.java:153)

[2020-09-24T23:11:25.924Z] 		at 
```

**Review by oleg-nenashev — APPROVED** [review]
LGTM. Fine to ship now, or should I wait for other changes to be ready?

**Comment by jglick** [comment]
> GC overhead limit exceeded

Try `useAci: true`?

> Fine to ship now

Yes.

**Comment by oleg-nenashev** [comment]
> Try useAci: true?

Might be. #143 for now

**Pull request merged**
