### PR TITLE
Add GET Roles and UnassignRole to REST API

### PR DESCRIPTION
**Pull request by LegallGuillaume**
I added the unassign to api with 
Example: curl -X POST localhost:8080/role-strategy/strategy/unassignRole --data "type=globalRoles&amp;roleName=AMD&amp;sid=username"

and I added the GET function api to return all roles and their groups with
Example: curl -X GET localhost:8080/role-strategy/strategy/getAllRoles
Result json: {roleName: ['group1', 'group2'], roleName : ''}

### CODE REVIEW

**Comment by LegallGuillaume** [comment]
@oleg-nenashev hi, don't forget to tell me if it's possible.

**Comment by LegallGuillaume** [comment]
@oleg-nenashev, I removed unnecessary comments, because we need to get a data from getAllRoles function, we not to send a data with POST. Sorry again I missed it at proofreading

**Comment by LegallGuillaume** [comment]
@oleg-nenashev did you tested this pull request ?

**Comment by oleg-nenashev** [comment]
Nope, I have not. Sorry about the delay, there were lots of activities going in the Jenkins core and security releases.

**Comment by oleg-nenashev** [comment]
I hope to find some time for the plugins on the weekend

**Comment by LegallGuillaume** [comment]
No problem :+1:  :)

**Comment by hpejustin** [comment]
When i run jenkins with tomcat, when i try to use this API, i got 404 error. The command: curl -X GET 15.114.100.53:8080/role-strategy/strategy/allRoles or curl -X GET -u admin:devops 15.114.100.53:8080/jenkins/role-strategy/strategy/allRoles, is there any thing wrong?

**Comment by LegallGuillaume** [comment]
hi,
it's
> curl -X localhost:8080/role-strategy/strategy/getAllRoles

The maintener has forgotten 'get' in front of allRoles.

**Comment by oleg-nenashev** [comment]
Hmm, `allRoles` should actually work as well... Maybe it depends on the Stapler version in the Jenkins core. @hpejustin which Jenkins version do you use?

**Comment by hpejustin** [comment]
Jenkins ver. 2.60.2 @oleg-nenashev , i deploy my jenkins with jenkins.war in the tomcat folder ../webapps/jenkins, so i access it whit http://15.114.100.53:8080/jenkins, but i can not get correct result when i use the command previous write there.

**Comment by hpejustin** [comment]
thanks all, i got the right result now, maybe some proxy reason, it is so nice of you all.

**Comment by fildaben** [comment]
This is great that we can pull all the global roles using role-strategy/strategy/getAllRoles, however, can you also expose getting all the project or item roles?

**Comment by LahariGuntha** [comment]
Hi,

Is there a rest api call to assign a particular role to a person in a particular project???

**Comment by oleg-nenashev** [comment]
> This is great that we can pull all the global roles using role-strategy/strategy/getAllRoles, however, can you also expose getting all the project or item roles?

I think we "just" need to implement export logic for that.

> Is there a rest api call to assign a particular role to a person in a particular project???

Nope, the plugin operates on regexp basis. You would have to create a new role in order to define permissions for particular project. [Ownership-based security](https://github.com/jenkinsci/ownership-plugin/blob/master/doc/OwnershipBasedSecurity.md) works it around by project-specific security

**Comment by angbamfield** [comment]
Has getting item roles/project roles been possible yet? also are we able to add/remove  project/item roles or is it just globalroles for now for all aspects for the api?

**Pull request merged**
