### PR TITLE
[JENKINS-19409] - Added option, which makes plugin to convert all SIDs to the lower-case

### PR DESCRIPTION
**Pull request by oleg-nenashev**
Resolves: https://issues.jenkins-ci.org/browse/JENKINS-19409

Signed-off-by: Oleg Nenashev nenashev@synopsys.com

### CODE REVIEW

**Comment by mpapo** [comment]
We're waiting for this PR. Is-it possible to merge it ? 
Thanks

**Comment by oleg-nenashev** [comment]
This PR needs some additional work to be merged.
I think we need "case insensitive" configuration instead of the conversion.

I'll try to do it as a part of the next release (no ETA).
If you want, I can provide a custom build with the patch

**Comment by sesto** [comment]
Are there any plans to resolve the conflicts and merge in the nearest future? We also have the problem of case sensitivity

**Comment by oleg-nenashev** [comment]
Unfortunately It's not in my priority list. If somebody is ready to get this PR finalized, I will be happy to review the code and integrate it if acceptable

**Comment by mawinter69** [comment]
replaced by #225

**Pull request closed without merging**
