### PR TITLE
User/group regex pattern support

### PR DESCRIPTION
**Pull request by aerodinesh**
- [ ] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [ ] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
-      If I have to assign a role to all of my employees using one rule, using this change we can specify using regex
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

Sorry I am not well versed about open source policies. It would be very nice of anyone if they could take up this idea, and properly do the contribution.

Thanks again for all the community for selfless contributions.

### CODE REVIEW

**Review by AbhyudayaSharma — CHANGES_REQUESTED** [review]
Hi. This PR will lead to a significant slowdown in the plugin's performance and will also change the existing behaviour. Could you not put all members into a group instead?

**Comment by aerodinesh** [comment]
Oh, yeah I didnt consider performance impact, my bad. Yes, like you said we can create groups and use in regular authentication scenario, it works.
However in our setup we auth using google oauth2, and in that case somehow I could not find a way to create groups and pull users to them, maybe I need more info there. So, I have deployed this change locally and it helped me.
But yeah, only if it could help the community without side-effects we shud consider this :)
Thank you for the feedback.

**Comment by aerodinesh** [comment]
Screenshot 2022-05-24 5 25 48 PM

This is how I used on our jenkins setup and it helped us to give access to our gsuite users through one rule.

**Comment by aerodinesh** [comment]
ok, closing this.

**Pull request closed without merging**
